// src/pages/api/games.js
export default function handler(req, res) {
  const games = [
    {
      id: 7322198644,
      rootPlaceId: 101932641046826,
      name: "Cheesecake Factory Tycoon!",
      description:
        "Welcome to Cheesecake Factory Tycoon! 🍰\n\n🧁 Bake cheesecakes \n👑 become the ultimate baker! 👑\n💵 JOIN GROUP FOR 50% CASH BOOST 💵\n🍓 JOIN THE GROUP FOR THE LATEST CODES. 🍓 \n💾 progress is saved automatically 💾 \n💗 Use These Codes after Joining the Group! JOINED \n\nIf you enjoyed the game, don't forget to 😝  Like, 💞 Favorite, and 🧀 Follow!\n\nチーズケーキファクトリータイクーン！\nเกมเจ้าพ่อโรงงานชีสเค้ก!\n치즈케이크 팩토리 타이쿤!\n¡El magnate de la fábrica de tartas de queso!\nМагнат фабрики чизкейков!\n\nTags: Baking, Chef, Restaurant, Cooking, Cute, Kawaii, Chibi, Kitty, Show off, Icons, Famous, Fame, Fashion, Dress to Impress, Dress Up, Compete, Fashion, Cake Off!, Make a Cake And Feed the Giant Noob Make a Cake!, and Bakers Valley",
      sourceName: null,
      sourceDescription: null,
      creator: {
        id: 33447943,
        name: "best tycoons studio",
        type: "Group",
        isRNVAccount: false,
        hasVerifiedBadge: false,
      },
      price: null,
      allowedGearGenres: ["All"],
      allowedGearCategories: [],
      isGenreEnforced: false,
      copyingAllowed: false,
      playing: 0,
      visits: 252389,
      maxPlayers: 4,
      created: "2025-03-03T03:36:24.373Z",
      updated: "2025-05-01T07:11:33.143Z",
      studioAccessToApisAllowed: false,
      createVipServersAllowed: false,
      universeAvatarType: "MorphToR15",
      genre: "All",
      genre_l1: "Simulation",
      genre_l2: "Tycoon",
      isAllGenre: true,
      isFavoritedByUser: false,
      favoritedCount: 3123,
    },
    {
      id: 7306157266,
      rootPlaceId: 75276479158432,
      name: "Prove Snow White Wrong by being PRETTY",
      description:
        "💄 Prove Snow White Wrong by being PRETTY 💄 \n\nSnow white thinks she is the prettiest of them all... to prove her wrong you sell makeup to become the most pretty! ✨\n\n💅 JOIN GROUP FOR 50% CASH BOOST 💅 \n🎀 JOIN THE GROUP FOR THE LATEST CODES. 🎀 \n💖 USE CODE JOINED AFTER JOINING THE GROUP 💖 \n💾  progress is saved automatically 💾 \n👍 leave a like and favorite if you want more updates, we appreciate it <3 👍 \n\nmirror mirror on the wall.... whats the worst movie of them all?🪞\nTHE NEW SNOW WHITE MOVIE SUCKS💔\n\nInspired by badass experiences, joshua, dress to impress, Snow White Movie\nБелоснежка симпатичный магнат\n백설공주 예쁜 재벌\n白雪姫のかわいい大物\nเจ้าพ่อสาวสวยสโนว์ไวท์",
      sourceName: null,
      sourceDescription: null,
      creator: {
        id: 33447943,
        name: "best tycoons studio",
        type: "Group",
        isRNVAccount: false,
        hasVerifiedBadge: false,
      },
      price: null,
      allowedGearGenres: ["All"],
      allowedGearCategories: [],
      isGenreEnforced: false,
      copyingAllowed: false,
      playing: 0,
      visits: 493514,
      maxPlayers: 4,
      created: "2025-02-28T09:29:12.863Z",
      updated: "2025-06-22T03:10:04.183Z",
      studioAccessToApisAllowed: false,
      createVipServersAllowed: false,
      universeAvatarType: "MorphToR15",
      genre: "All",
      genre_l1: "Simulation",
      genre_l2: "Tycoon",
      isAllGenre: true,
      isFavoritedByUser: false,
      favoritedCount: 2463,
    },
    {
      id: 6845302359,
      rootPlaceId: 101099707786197,
      name: "Sell Guns In Da Hood Tycoon 🔫",
      description:
        "🔫 Welcome to Sell Guns In Da Hood Tycoon! 🔫\n\n🎮 JOIN GROUP FOR 50% CASH BOOST 🎮\n💯 JOIN THE GROUP FOR THE LATEST CODES. 💯\n💿 Use These Codes after Joining the Group! JOINED \n💾 progress is saved automatically 💾 \n👍 leave a like and favorite if you want more updates, we appreciate it <3 👍\n\nDa Hood, Gun Armory Tycoon War Tycoon Military Tycoon Warfare Tycoon RIVALS Tha Bronx 2 💯\n\nInspired by badass experiences and joshua, and da hood, South Bronx: The Trenches❗, Hood Modded, OHIO, SELL POOP TYCOON! Inspired by 🛒Retail Tycoon 2, 🍕 Pizzeria Tycoon 2, 🍣 Sushi Shop Tycoon, Pet Store Tycoon, 🍡 Mochi Shop Tycoon, 🥪 Sandwich Tycoon, [UPD]\nTags: pizza restaurant real world roleplay pizzeria cafe role play simulation cafe factory pizza worker pizza social hangout sushi game simulator world hotel cafe popular tycoon cafe hotel tycoon tycoon tycoon tycoon tycoon tycoon tycoon tycoon tycoon tycoon tycoon",
      sourceName: null,
      sourceDescription: null,
      creator: {
        id: 33447943,
        name: "best tycoons studio",
        type: "Group",
        isRNVAccount: false,
        hasVerifiedBadge: false,
      },
      price: null,
      allowedGearGenres: ["All"],
      allowedGearCategories: [],
      isGenreEnforced: false,
      copyingAllowed: false,
      playing: 3,
      visits: 1854121,
      maxPlayers: 4,
      created: "2024-11-27T02:26:44.333Z",
      updated: "2025-03-28T05:35:56.793Z",
      studioAccessToApisAllowed: false,
      createVipServersAllowed: false,
      universeAvatarType: "MorphToR15",
      genre: "All",
      genre_l1: "Simulation",
      genre_l2: "Tycoon",
      isAllGenre: true,
      isFavoritedByUser: false,
      favoritedCount: 213173,
    },
    {
      id: 6802252366,
      rootPlaceId: 133974069575437,
      name: "Sell Toilets to RULE THE WORLD 🚽🌎",
      description:
        'You\'re a loser. Nobody likes you. You have no friends and ur broke. 😔 BUT you get a genius idea to start selling TOILETS (??) to people on the street. Make conveyors and build a factory, selling TOILETS to people. Prove everybody wrong... get rich and RULE THE WORLD. (with TOILETS) (by being a little bit morally sus)\n🚽\n\n🎮 JOIN GROUP TO GET 50% MORE CASH 🎮\n👍 like if u want more updates :) 👍\n💾 Progress is automatically saved 💾 \n\nwater tycoon inspired by My Toilet and "prove dad wrong tycoon / prove mom wrong tycoon" games\n\nMy Toilet 🚽 Shop Tycoon!! Sell Toilets and become the best and biggest toilet flusher manufacturer factory ever! 💩\nTags: Toilet, Tycoon, Skibidi, Bathroom, Manager, Employees, Workers, Clean, Fix\nMake a good public bathroom\n\nигра продай фабрику туалетов смешная\nขายเกมโรงงานห้องน้ำตลกๆ\n面白いトイレ工場ゲームを販売します\nvender juegos de fábrica de baños divertidos',
      sourceName: null,
      sourceDescription: null,
      creator: {
        id: 33447943,
        name: "best tycoons studio",
        type: "Group",
        isRNVAccount: false,
        hasVerifiedBadge: false,
      },
      price: null,
      allowedGearGenres: ["All"],
      allowedGearCategories: [],
      isGenreEnforced: false,
      copyingAllowed: false,
      playing: 0,
      visits: 707166,
      maxPlayers: 4,
      created: "2024-11-16T10:47:24.31Z",
      updated: "2025-01-11T20:15:50.94Z",
      studioAccessToApisAllowed: false,
      createVipServersAllowed: false,
      universeAvatarType: "MorphToR15",
      genre: "All",
      genre_l1: "Simulation",
      genre_l2: "Tycoon",
      isAllGenre: true,
      isFavoritedByUser: false,
      favoritedCount: 1255,
    },
    {
      id: 6802250269,
      rootPlaceId: 77392801527636,
      name: "🍔 Burger Place Tycoon",
      description:
        "Welcome to 🍔 Burger Place Tycoon!\n\n🍔 Grill burgers and serve up smiles!\n👨‍🍳 Hire chefs and cashiers to grow your restaurant!\n💵 Earn money and upgrade your burger empire!\n🧹 Keep your burger place clean and customers happy!\n\nCodes: STARTBURGER, GRILLTIME\n👍 LIKE and FAVORITE for awesome updates and rewards!\n\nInspired by amazing tycoon adventures and the Roblox classics!\nAlso inspired by: 🍔 Burgeria Tycoon, SELL BURGERS TO PROVE MOM WRONG, Burger Store Tycoon, Cook Burgers, and Sandwich Restaurant Tycoon!",
      sourceName: null,
      sourceDescription: null,
      creator: {
        id: 33447943,
        name: "best tycoons studio",
        type: "Group",
        isRNVAccount: false,
        hasVerifiedBadge: false,
      },
      price: null,
      allowedGearGenres: ["All"],
      allowedGearCategories: [],
      isGenreEnforced: false,
      copyingAllowed: false,
      playing: 17,
      visits: 1159622,
      maxPlayers: 4,
      created: "2024-11-16T10:46:46.93Z",
      updated: "2025-03-21T01:44:54.153Z",
      studioAccessToApisAllowed: false,
      createVipServersAllowed: false,
      universeAvatarType: "MorphToR15",
      genre: "All",
      genre_l1: "Simulation",
      genre_l2: "Tycoon",
      isAllGenre: true,
      isFavoritedByUser: false,
      favoritedCount: 86317,
    },
    {
      id: 6559720859,
      rootPlaceId: 136647016559133,
      name: "Bake Cakes and Prove Mom Wrong 🎂",
      description:
        "Welcome to Bake Cakes and Prove Mom Wrong 🎂\n\n🧁 Bake and Create your dream cake\n⭐ Show off your cakes\n🍓 And become the ultimate baker!\n🎮 JOIN GROUP FOR 50% CASH BOOST 🎮\n🎮 JOIN THE GROUP FOR THE LATEST CODES. 🎮 \n💾 progress is saved automatically 💾 \n💗 Use These Codes after Joining the Group! JOINED \n\nIf you enjoyed the game, don't forget to 😝  Like, 💞 Favorite, and 🗣️ Follow!\n\nอบเค้กที่ดี\n맛있는 케이크를 굽다\nおいしいケーキを焼く\n\nTags: Baking, Chef, Restaurant, Cooking, Cute, Kawaii, Chibi, Kitty, Show off, Icons, Famous, Fame, Fashion, Dress Up, Compete, Fashion\nInspired by [UPD] Cake Off!, ★Make a Cake And Feed the Giant Noob★, Make a Cake! [Update!], Bakers Valley",
      sourceName: null,
      sourceDescription: null,
      creator: {
        id: 33447943,
        name: "best tycoons studio",
        type: "Group",
        isRNVAccount: false,
        hasVerifiedBadge: false,
      },
      price: null,
      allowedGearGenres: ["All"],
      allowedGearCategories: [],
      isGenreEnforced: false,
      copyingAllowed: false,
      playing: 7,
      visits: 3103912,
      maxPlayers: 4,
      created: "2024-09-15T19:25:15.41Z",
      updated: "2025-04-01T08:32:42.727Z",
      studioAccessToApisAllowed: false,
      createVipServersAllowed: false,
      universeAvatarType: "MorphToR15",
      genre: "All",
      genre_l1: "Simulation",
      genre_l2: "Tycoon",
      isAllGenre: true,
      isFavoritedByUser: false,
      favoritedCount: 10041,
    },
    {
      id: 6559720451,
      rootPlaceId: 103999149462324,
      name: "Sell Fish to RULE THE WORLD 🐟🌎",
      description:
        'You\'re a loser. Nobody likes you. You have no friends and ur broke. 😔 BUT you get a genius idea to start selling fish (??) to people on the street (which is also in the middle of the desert). Make conveyors and build a factory, selling fish to people. Prove everybody wrong... get rich and RULE THE WORLD. (with fish) (by being a little bit morally questionable):🐟\n\n🎮 JOIN GROUP TO GET 125% CASH 🎮\n👍 like if u want more updates :) 👍\n💾 Progress is automatically saved 💾 \n\nINSPIRED BY 🦈 Fisch\n\nwater tycoon inspired by universal paperclips and "prove dad wrong tycoon / prove mom wrong tycoon" games',
      sourceName: null,
      sourceDescription: null,
      creator: {
        id: 33447943,
        name: "best tycoons studio",
        type: "Group",
        isRNVAccount: false,
        hasVerifiedBadge: false,
      },
      price: null,
      allowedGearGenres: ["All"],
      allowedGearCategories: [],
      isGenreEnforced: false,
      copyingAllowed: false,
      playing: 4,
      visits: 1839463,
      maxPlayers: 6,
      created: "2024-09-15T19:25:07.777Z",
      updated: "2025-05-17T09:44:40.917Z",
      studioAccessToApisAllowed: false,
      createVipServersAllowed: false,
      universeAvatarType: "MorphToR15",
      genre: "All",
      genre_l1: "Simulation",
      genre_l2: "Tycoon",
      isAllGenre: true,
      isFavoritedByUser: false,
      favoritedCount: 2742,
    },
    {
      id: 6392747863,
      rootPlaceId: 18874245476,
      name: "🔫 Gun Store Tycoon",
      description:
        "🔫 Welcome to Gun Store Tycoon! 🔫\n\n🎮 JOIN GROUP FOR 50% CASH BOOST 🎮\n💯 JOIN THE GROUP FOR THE LATEST CODES. 💯\n💿 Use These Codes after Joining the Group! JOINED \n💾 progress is saved automatically 💾 \n👍 leave a like and favorite if you want more updates, we appreciate it <3 👍\n\nGun Armory Tycoon War Tycoon Military Tycoon Warfare Tycoon RIVALS\n\nInspired by badass experiences and joshua, and da hood, South Bronx: The Trenches❗,  Hood Modded, SELL POOP TYCOON! Inspired by 🛒Retail Tycoon 2, 🍕 Pizzeria Tycoon 2, 🍣 Sushi Shop Tycoon, Pet Store Tycoon, 🍡 Mochi Shop Tycoon, 🍔 Burger Store Tycoon, [🎉 JANITOR] ☕ Coffee Shop Tycoon, 🥪 Sandwich Tycoon, [UPD] Cake Off!, , Make a Cake! [Update!]\nTags: pizza restaurant real world roleplay pizzeria cafe role play simulation cafe factory pizza worker pizza social hangout sushi game simulator world hotel cafe popular tycoon cafe hotel tycoon tycoon tycoon tycoon tycoon tycoon tycoon tycoon tycoon tycoon tycoon",
      sourceName: null,
      sourceDescription: null,
      creator: {
        id: 33447943,
        name: "best tycoons studio",
        type: "Group",
        isRNVAccount: false,
        hasVerifiedBadge: false,
      },
      price: null,
      allowedGearGenres: ["All"],
      allowedGearCategories: [],
      isGenreEnforced: false,
      copyingAllowed: false,
      playing: 48,
      visits: 5924851,
      maxPlayers: 4,
      created: "2024-08-09T13:50:25.013Z",
      updated: "2025-05-26T22:17:32.48Z",
      studioAccessToApisAllowed: false,
      createVipServersAllowed: false,
      universeAvatarType: "MorphToR15",
      genre: "All",
      genre_l1: "Simulation",
      genre_l2: "Tycoon",
      isAllGenre: true,
      isFavoritedByUser: false,
      favoritedCount: 659125,
    },
    {
      id: 6392744410,
      rootPlaceId: 18874235569,
      name: "⚽ Be A Pro To Prove Ronaldo Wrong",
      description:
        'Welcome to Ronaldo V MR Beast Football Tycoon ⚽!\n\n⚽ You see stars like Ronaldo and Messi get goals on TV. You decide to become the ULTIMATE FOOTBALL STAR and prove everyone wrong. give all your friends football kits to train them and make the best team ever! ,Become Better than Ronaldo and Prove Mom Wrong and Prove Dad Wrong by going PRO in football and soccer ⚽\n\n👍LEAVE A LIKE AND FAVORITE FOR MORE UPDATES!! 👍 \n\n⚽Become a football PRO!\n🎮 JOIN GROUP AND LIKE THE GAME FOR 50% CASH BOOST 🎮\n💕 JOIN THE GROUP FOR THE LATEST CODES 💕\n💾 Progress is saved automatically 💾 \n\nCodes: "Release", "Joined" \nJOIN THE GROUP FOR THE LATEST CODES.\n\nInspired by badass experiences and joshua, and ⚽turn pro proving messi and ronaldo wrong, Realistic Street Soccer, [Ranked] Super League Soccer Tycoon\n\ntags: Tycoon, FIFA, Football, Soccer, Tycoon, Football Tycoon, christmas, NBA',
      sourceName: null,
      sourceDescription: null,
      creator: {
        id: 33447943,
        name: "best tycoons studio",
        type: "Group",
        isRNVAccount: false,
        hasVerifiedBadge: false,
      },
      price: null,
      allowedGearGenres: ["All"],
      allowedGearCategories: [],
      isGenreEnforced: false,
      copyingAllowed: false,
      playing: 0,
      visits: 1983055,
      maxPlayers: 4,
      created: "2024-08-09T13:49:33.493Z",
      updated: "2025-03-10T02:43:58.28Z",
      studioAccessToApisAllowed: false,
      createVipServersAllowed: false,
      universeAvatarType: "MorphToR15",
      genre: "All",
      genre_l1: "Simulation",
      genre_l2: "Tycoon",
      isAllGenre: true,
      isFavoritedByUser: false,
      favoritedCount: 2480,
    },
    {
      id: 6392743950,
      rootPlaceId: 18874233939,
      name: "SELL WIGS TO CURE BALDNESS",
      description:
        '💅One day while trying to be a the best beauty queen, the other baddies decide to bully you. You must climb the ranks and become the best wig and hair makeup artist to prove your family wrong and win them back.\n\n👍LEAVE A LIKE AND FAVORITE TO BE A BADDIE AND FOR MORE UPDATES!! 👍 \n\n🎮 JOIN GROUP AND LIKE THE GAME FOR 50% CASH BOOST 🎮\n💕 JOIN THE GROUP FOR THE LATEST CODES 💕\n💾 Progress is saved automatically 💾 \nCodes: "Release", "Joined" \nJOIN THE GROUP FOR THE LATEST CODES. THIRD FLOOR AND BASEMENT COMING SOON!!!\n\nInspired by\n[TAGS: SALON DRESS UP MAKEOVER STYLE COMPETITION 2 PLAYER MAKEUP BEAUTY GLAM CLOTHING]\nKeywords: dressup, salon, avatar customization, nails, hair, makeup, roleplay, chatroom, hangout, girly, dress to impress',
      sourceName: null,
      sourceDescription: null,
      creator: {
        id: 33447943,
        name: "best tycoons studio",
        type: "Group",
        isRNVAccount: false,
        hasVerifiedBadge: false,
      },
      price: null,
      allowedGearGenres: ["All"],
      allowedGearCategories: [],
      isGenreEnforced: false,
      copyingAllowed: false,
      playing: 0,
      visits: 2060674,
      maxPlayers: 4,
      created: "2024-08-09T13:49:26.127Z",
      updated: "2024-11-20T13:22:11.38Z",
      studioAccessToApisAllowed: false,
      createVipServersAllowed: false,
      universeAvatarType: "MorphToR15",
      genre: "All",
      genre_l1: "Simulation",
      genre_l2: "Tycoon",
      isAllGenre: true,
      isFavoritedByUser: false,
      favoritedCount: 7877,
    },
    {
      id: 6384416902,
      rootPlaceId: 18849014225,
      name: "✏️ Make pencils to RULE THE WORLD!",
      description:
        "✏️Make Pencils To Rule The World✏️\n\nYour dad doesn't think you will make pencils the rule the world and he thinks you will FAIL. to prove him wrong, you start building the Best pencil factory ever to rule the World.... \n\nUPDATE 1\n- RELEASED!\n\n🎮 JOIN GROUP FOR 50% CASH BOOST 🎮\n 🎮 JOIN THE GROUP FOR THE LATEST CODES. 🎮 \n💗 Use These Codes after Joining the Group! JOINED \n💾 progress is saved automatically 💾 \n👍 leave a like and favorite if you want more updates, we appreciate it <3 👍\n\nLead Creator: TUBSYOLO2 https://www.roblox.com/users/1118823050\nDev: grah_grah https://www.roblox.com/users/1459474140/profile\n\nボバ茶を作る\n보바차를 만들어 보세요\nทำชาไข่มุก\n\nInspired by badass experiences and joshua, and make phones to prove dad wrong",
      sourceName: null,
      sourceDescription: null,
      creator: {
        id: 33447943,
        name: "best tycoons studio",
        type: "Group",
        isRNVAccount: false,
        hasVerifiedBadge: false,
      },
      price: null,
      allowedGearGenres: ["All"],
      allowedGearCategories: [],
      isGenreEnforced: false,
      copyingAllowed: false,
      playing: 0,
      visits: 131428,
      maxPlayers: 4,
      created: "2024-08-07T17:03:19.357Z",
      updated: "2025-04-03T03:40:30.71Z",
      studioAccessToApisAllowed: false,
      createVipServersAllowed: false,
      universeAvatarType: "MorphToR15",
      genre: "All",
      genre_l1: "Simulation",
      genre_l2: "Tycoon",
      isAllGenre: true,
      isFavoritedByUser: false,
      favoritedCount: 738,
    },
    {
      id: 6312814057,
      rootPlaceId: 18631220436,
      name: "💅Fashion Tycoon 2",
      description:
        "Become a real Baddie, Hang Out, Get Money 💅\n\nDa baddies start bullying you for not being a real gurl on the streets, you decide to sell purses to make it out the hood, become a baddie and prove the gurls wrong. Start your journey now!!!\n\n🎮 JOIN GROUP FOR 50% CASH BOOST 🎮\n💕 JOIN THE GROUP FOR THE LATEST CODES. 💕\n💿 Use These Codes after Joining the Group! JOINED \n💾 progress is saved automatically 💾 \n👍 leave a like and favorite if you want more updates, we appreciate it <3 👍\n\n💅💅🏻💅🏼💅🏽💅🏾💅🏿 QUEEN!!!\n\n女の子のゲームの悪役にイ\n여자 악당이 되어 여자 게임 악당에서 영감을 \nกลายเป็นสาวร้ายและขายกระเป๋า ได้รับแรงบันดาลใจจากเกมสาวร\nстаньте девочкой-злодейкой и продавайте кошельки, вдохновленные девчачьими играми-злодейками\n\nInspired by badass experiences and joshua, and BADDIES, Baddies, Florida, Bad Girls, South, hood, west, battlegrounds, Roleplay, Hosted, Freeplay.\nhood, South Bronx: The Trenches❗,  Hood Modded",
      sourceName: null,
      sourceDescription: null,
      creator: {
        id: 33447943,
        name: "best tycoons studio",
        type: "Group",
        isRNVAccount: false,
        hasVerifiedBadge: false,
      },
      price: null,
      allowedGearGenres: ["All"],
      allowedGearCategories: [],
      isGenreEnforced: false,
      copyingAllowed: false,
      playing: 0,
      visits: 1440170,
      maxPlayers: 4,
      created: "2024-07-24T07:49:11.963Z",
      updated: "2025-04-21T22:26:34.967Z",
      studioAccessToApisAllowed: false,
      createVipServersAllowed: false,
      universeAvatarType: "MorphToR15",
      genre: "All",
      genre_l1: "Simulation",
      genre_l2: "Tycoon",
      isAllGenre: true,
      isFavoritedByUser: false,
      favoritedCount: 4505,
    },
    {
      id: 6305461832,
      rootPlaceId: 18608611044,
      name: "🍪 Sell Cookies and Prove Mom Wrong",
      description:
        "🍪 Sell Cookies to PROVE MOM WRONG! 🍪 \n\nYour mom doesn't want you to sell cookies and says that ur not a good baker... to prove her wrong you cook the best cookies and sell it to people and become the best cookie baker to ever exist! ✨ \n\n👨‍🍳 JOIN GROUP FOR 50% CASH BOOST 👨‍🍳 \n🥣 JOIN THE GROUP FOR THE LATEST CODES. 🥣 \n💖 USE CODE JOINED AFTER JOINING THE GROUP 💖 \n💾 progress is saved automatically 💾 \n\n👍 leave a like and favorite if you want more updates, we appreciate it <3 👍 \n\nUpdate: \n- removed drake \n- deleted amber heard \n\nおいしいクッキーを焼く \n맛있는 쿠키를 굽다 \nиспечь вкусное печенье \nอบคุกกี้แสนอร่อย \nHornear deliciosas galletas I\n\nnspired by badass experiences and joshua, and Cookie Tower 🍪,🏄 BAKE DA BABY, Cake Off! [FRIENDS]",
      sourceName: null,
      sourceDescription: null,
      creator: {
        id: 33447943,
        name: "best tycoons studio",
        type: "Group",
        isRNVAccount: false,
        hasVerifiedBadge: false,
      },
      price: null,
      allowedGearGenres: ["All"],
      allowedGearCategories: [],
      isGenreEnforced: false,
      copyingAllowed: false,
      playing: 7,
      visits: 5022813,
      maxPlayers: 4,
      created: "2024-07-22T18:10:42.08Z",
      updated: "2025-04-25T04:45:16.553Z",
      studioAccessToApisAllowed: false,
      createVipServersAllowed: false,
      universeAvatarType: "MorphToR15",
      genre: "All",
      genre_l1: "Simulation",
      genre_l2: "Tycoon",
      isAllGenre: true,
      isFavoritedByUser: false,
      favoritedCount: 11399,
    },
    {
      id: 6305459600,
      rootPlaceId: 18608603754,
      name: "Computer Tycoon 2",
      description:
        "your dad says you'll never be successful with your trash laptops. Time to show him what's up. \nBuild your own laptop empire and become the biggest tech mogul in Robloxia. \n\n💸 JOIN GROUP FOR A 50% CASH BOOST 👍 \nJOIN THE GROUP FOR THE LATEST CODES.\n\n Lead Creator: robI0x_Studio https://www.roblox.com/users/628627550 \n\nUpdate 1: \n\n- Removed Kanye\n\n Inspired by badass experiences and Joshua. \n\nノートパソコンを販売して父親が間違っていることを証明し、マイクロソフトやアップルになる\n노트북을 팔아서 아빠가 틀렸다는 걸 증명하 고 마이크로소프트와 애플이 되자\n Vender computadoras portátiles y demostrarle a papá que está equivocado, convertirse en Microsoft y Apple.\n ขายโน้ตบุ๊กและพิสูจน์ว่าพ่อคิดผิด กลายเป็นไมโครซอฟต์และแอปเปิล\n\nTags: 2 Player Computer Tycoon",
      sourceName: null,
      sourceDescription: null,
      creator: {
        id: 33447943,
        name: "best tycoons studio",
        type: "Group",
        isRNVAccount: false,
        hasVerifiedBadge: false,
      },
      price: null,
      allowedGearGenres: ["All"],
      allowedGearCategories: [],
      isGenreEnforced: false,
      copyingAllowed: false,
      playing: 0,
      visits: 520524,
      maxPlayers: 4,
      created: "2024-07-22T18:10:07.567Z",
      updated: "2025-01-12T12:39:05.537Z",
      studioAccessToApisAllowed: false,
      createVipServersAllowed: false,
      universeAvatarType: "MorphToR15",
      genre: "All",
      genre_l1: "Simulation",
      genre_l2: "Tycoon",
      isAllGenre: true,
      isFavoritedByUser: false,
      favoritedCount: 2059,
    },
    {
      id: 6305458488,
      rootPlaceId: 18608599128,
      name: "💎Sell Bling and Prove Da Hood Wrong",
      description:
        "💎 Sell and Make Bling in da hood tycoon and prove da hood wrong 🥶 \n\nDa hood starts bullying you for not being Drippy on the streets, you decide to sell BLING to make it out da hood and prove the haters wrong. Start your journey now!!!\n\n🎮 JOIN GROUP FOR 50% CASH BOOST 🎮\n💯 JOIN THE GROUP FOR THE LATEST CODES. 💯\n💿 Use These Codes after Joining the Group! JOINED \n💾 progress is saved automatically 💾 \n👍 leave a like and favorite if you want more updates, we appreciate it <3 👍\n\nUpdate 1: \n- Removed Drake\n\nキラキラして滴るほどになる\n현지 오두막에서 블링블링을 만들고 흠뻑 젖어보세요\nกลายเป็นน้ำหยดและขายของในเครื่องดูดควัน\nсделать побрякушку в капюшоне\nConviértete en un goteo y vende joyas en el barrio.\nBecome a drippy and sell bling in da hood\n\nInspired by badass experiences and joshua, and da hood, South Bronx: The Trenches❗,  Hood Modded, SELL POOP TYCOON!, Bloxspin, block spin, bloxspin, blox spin, blockspin",
      sourceName: null,
      sourceDescription: null,
      creator: {
        id: 33447943,
        name: "best tycoons studio",
        type: "Group",
        isRNVAccount: false,
        hasVerifiedBadge: false,
      },
      price: null,
      allowedGearGenres: ["All"],
      allowedGearCategories: [],
      isGenreEnforced: false,
      copyingAllowed: false,
      playing: 10,
      visits: 4195048,
      maxPlayers: 4,
      created: "2024-07-22T18:09:49.16Z",
      updated: "2025-04-27T04:43:53.1Z",
      studioAccessToApisAllowed: false,
      createVipServersAllowed: false,
      universeAvatarType: "MorphToR15",
      genre: "All",
      genre_l1: "Simulation",
      genre_l2: "Tycoon",
      isAllGenre: true,
      isFavoritedByUser: false,
      favoritedCount: 391676,
    },
    {
      id: 6305457330,
      rootPlaceId: 18608595950,
      name: "Boba Shop Tycoon🧋",
      description:
        "🧋Welcome to boba shop store cafe Tycoon!🥤\n\nPrepare boba in your cafe store shop then serve it to customers! Make the best boba bubble tea store in town!!! 💗 \n\nUPDATE 1\n- Fixed Bugs!\n\n🎮 JOIN GROUP FOR 50% CASH BOOST 🎮\n 🎮 JOIN THE GROUP FOR THE LATEST CODES. 🎮 \n💗 Use These Codes after Joining the Group! JOINED \n💾 progress is saved automatically 💾 \n👍 leave a like and favorite if you want more updates, we appreciate it <3 👍\n\nร้านชาไข่มุกไข่มุก\n보바 버블티 카페\nタピオカ タピオカティー カフェ\n\nInspired by badass experiences and joshua, and bubble tea tycoon along with boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba",
      sourceName: null,
      sourceDescription: null,
      creator: {
        id: 33447943,
        name: "best tycoons studio",
        type: "Group",
        isRNVAccount: false,
        hasVerifiedBadge: false,
      },
      price: null,
      allowedGearGenres: ["All"],
      allowedGearCategories: [],
      isGenreEnforced: false,
      copyingAllowed: false,
      playing: 86,
      visits: 7657944,
      maxPlayers: 4,
      created: "2024-07-22T18:09:32.407Z",
      updated: "2025-06-24T16:10:21.57Z",
      studioAccessToApisAllowed: false,
      createVipServersAllowed: false,
      universeAvatarType: "MorphToR15",
      genre: "All",
      genre_l1: "Simulation",
      genre_l2: "Tycoon",
      isAllGenre: true,
      isFavoritedByUser: false,
      favoritedCount: 846553,
    },
    {
      id: 6130034762,
      rootPlaceId: 17887314952,
      name: "🗑️ Sell trash to RULE THE WORLD! 🌎✨",
      description:
        "🗑️ You’ve had enough of people believing that being poor prevents one from becoming wealthy. You were bullied for too long. To prove them wrong, you choose to recycle trash and show that you can improve the environment and earn money at the same time. 💸💸💸\n\n👍 LIKE THE GAME TO BRING BACK KANYE\n💵 JOIN THE GROUP FOR A 50% CASH BOOST\n📋 JOIN THE GROUP FOR THE LATEST UPDATES\n\nCodes: JOINED, RELEASE\n\n🌷Credits🌷\nYou - For playing the game\nUAEBallUBG - Config\nDevvinLua - Devving\nWebpotion - Group Owner\n\nInspired by badass experiences and joshua\n\nごみをリサイクルして成功を収めましょう\n쓰레기를 재활용하여 성공하십시오\nรีไซเคิลขยะและประสบความส\n",
      sourceName: null,
      sourceDescription: null,
      creator: {
        id: 33447943,
        name: "best tycoons studio",
        type: "Group",
        isRNVAccount: false,
        hasVerifiedBadge: false,
      },
      price: null,
      allowedGearGenres: ["All"],
      allowedGearCategories: [],
      isGenreEnforced: false,
      copyingAllowed: false,
      playing: 19,
      visits: 2516588,
      maxPlayers: 4,
      created: "2024-06-16T20:32:57.75Z",
      updated: "2025-06-24T12:32:31.483Z",
      studioAccessToApisAllowed: false,
      createVipServersAllowed: false,
      universeAvatarType: "MorphToR15",
      genre: "All",
      genre_l1: "Simulation",
      genre_l2: "Tycoon",
      isAllGenre: true,
      isFavoritedByUser: false,
      favoritedCount: 5091,
    },
    {
      id: 6130032302,
      rootPlaceId: 17887308189,
      name: "👜 Sell GUCCI and Prove Dad Wrong [FREAKY]",
      description:
        "👜 Sell and Make GUCCI fashion clothes in the hood tycoon and prove dad wrong 🥶\n\nDad starts shouting at you and wants to kick you out for not being succesfull, you decide to sell some fire GUCCI to make it out da hood and prove all those haters wrong. Start your journey now gang!!!\n\n🎮 JOIN GROUP FOR 50% CASH BOOST 💰\n💯 JOIN THE GROUP FOR THE LATEST CODES. 🥶\n💿 Use These Codes after Joining the Group! JOINED \n📺 progress is saved automatically 💾 \n👍 leave a like and favorite if you want more updates, we appreciate it <3 👍\n\nUpdate 1: \n- Removed Drake LOL\n\nグッチ ファッション\n구찌 패션\nแฟชั่นกุชชี่\nกลายเป็นนักเลงและขายเสื้อผ้าดีไซเนอร์\nギャングになってデザイナーの服を売る\n동네 거물에서 총을 만들고 갱스터가 되어보세요\n갱스터가 되어 디자이너 옷을 팔아\n\nInspired by badass experiences and joshua, and sells guns and prove da hood wrong and da hood, South Bronx: The Trenches❗,  Hood Modded, SELL POOP TYCOON!, MAKE DUMB FASHION TREND TO PROVE DAD WRONG, GUCCI",
      sourceName: null,
      sourceDescription: null,
      creator: {
        id: 33447943,
        name: "best tycoons studio",
        type: "Group",
        isRNVAccount: false,
        hasVerifiedBadge: false,
      },
      price: null,
      allowedGearGenres: ["All"],
      allowedGearCategories: [],
      isGenreEnforced: false,
      copyingAllowed: false,
      playing: 24,
      visits: 4060118,
      maxPlayers: 4,
      created: "2024-06-16T20:32:14.513Z",
      updated: "2025-03-25T02:27:31.233Z",
      studioAccessToApisAllowed: false,
      createVipServersAllowed: false,
      universeAvatarType: "MorphToR15",
      genre: "All",
      genre_l1: "Simulation",
      genre_l2: "Tycoon",
      isAllGenre: true,
      isFavoritedByUser: false,
      favoritedCount: 21723,
    },
    {
      id: 6130030337,
      rootPlaceId: 17887302440,
      name: "🍹 Make Smoothies and Prove Mom Wrong",
      description:
        "🥤Make and Sell Smoothies and Milkshakes to PROVE MOM WRONG! 🥤\n\nYour mom doesn't like your smoothies, and she says that you will FAIL in life. to prove her wrong, you start building the best Milkshake factory ever.... \n\n🎮 JOIN GROUP FOR 50% CASH BOOST 🎮\n🎮 JOIN THE GROUP FOR THE LATEST CODES. 🎮 \n💗 Use These Codes after Joining the Group! JOINED \n💾 progress is saved automatically 💾 \n👍 leave a like and favorite if you want more updates, we appreciate it <3 👍\n\nupdate: \n- removed drake\n- removed freakbob\n\n爽やかなスムージーを作る\nおいしいミルクシェイクを作る\n상큼한 스무디를 만들어보세요\n맛있는 밀크셰이크를 만들어보세요\nทำมิลค์เชคแสนอร่อย\nทำสมูทตี้แสนอร่อย\n\nInspired by badass experiences and joshua, and smoothie tycoon along with milkshake",
      sourceName: null,
      sourceDescription: null,
      creator: {
        id: 33447943,
        name: "best tycoons studio",
        type: "Group",
        isRNVAccount: false,
        hasVerifiedBadge: false,
      },
      price: null,
      allowedGearGenres: ["All"],
      allowedGearCategories: [],
      isGenreEnforced: false,
      copyingAllowed: false,
      playing: 11,
      visits: 2004213,
      maxPlayers: 4,
      created: "2024-06-16T20:31:45.587Z",
      updated: "2024-08-19T08:29:16.837Z",
      studioAccessToApisAllowed: false,
      createVipServersAllowed: false,
      universeAvatarType: "MorphToR15",
      genre: "All",
      genre_l1: "Simulation",
      genre_l2: "Tycoon",
      isAllGenre: true,
      isFavoritedByUser: false,
      favoritedCount: 4315,
    },
    {
      id: 6096513061,
      rootPlaceId: 17795218912,
      name: "Prove Mom Wrong by Selling Mochi 🍡",
      description:
        "🍡 Welcome to Mochi Shop Tycoon! 🌸\n\nCook mochi and sell it to people on the street. Eventually, expand your shop and sell tastier more flavors of mochi! Gain alot of money and prove mom wrong! \n\n💃 JOIN GROUP FOR 50% CASH BOOST AND CODES 💃\n💕 USE CODE JOINED AFTER JOINING THE GROUP 💕 \n💾  progress is saved automatically 💾 \n👍 leave a like and favorite if you want more updates, we appreciate it <3 👍 \n\nInspired by badass experiences and joshua \n\n売る もち, 餅\n떡을 팔다\nпродать моти\nขายโมจิ",
      sourceName: null,
      sourceDescription: null,
      creator: {
        id: 33447943,
        name: "best tycoons studio",
        type: "Group",
        isRNVAccount: false,
        hasVerifiedBadge: false,
      },
      price: null,
      allowedGearGenres: ["All"],
      allowedGearCategories: [],
      isGenreEnforced: false,
      copyingAllowed: false,
      playing: 789,
      visits: 21305041,
      maxPlayers: 4,
      created: "2024-06-09T15:51:52.6Z",
      updated: "2025-08-10T19:22:59.093Z",
      studioAccessToApisAllowed: false,
      createVipServersAllowed: false,
      universeAvatarType: "MorphToR15",
      genre: "All",
      genre_l1: "Simulation",
      genre_l2: "Tycoon",
      isAllGenre: true,
      isFavoritedByUser: false,
      favoritedCount: 62851,
    },
    {
      id: 6096510272,
      rootPlaceId: 17795211697,
      name: "Cookie Shop Tycoon 🍪",
      description:
        "🍪 Welcome to Cookie Shop Store cafe Tycoon! 💗\n\nPrepare Cookies in your shop then serve it to customers! Make the best cookies in town!!! 💗 \n\nUPDATE 1\n- Fixed Bugs!\n\n🎮 JOIN GROUP FOR 50% CASH BOOST 🎮\n 🎮 JOIN THE GROUP FOR THE LATEST CODES. 🎮 \n💗 Use These Codes after Joining the Group! JOINED \n💾 progress is saved automatically 💾 \n👍 leave a like and favorite if you want more updates, we appreciate it <3 👍\n\nร้านคุ้กกี้\n쿠키 가게\nクッキーショップ\n\nInspired by badass experiences and joshua, and cookie store tycoon along with cookies cookies cookies cookies cookies cookies cookies cookies cookies cookies cookies cookies cookies cookies cookies cookies cookies cookies cookies cookies cookies cookies cookies cookies cookies cookies cookies cookies cookies cookies cookies cookies cookies cookies cookies cookies cookies cookies cookies cookies cookies cookies cookies cookies cookies cookies cookies cookies cookies cookies cookies cookies cookies",
      sourceName: null,
      sourceDescription: null,
      creator: {
        id: 33447943,
        name: "best tycoons studio",
        type: "Group",
        isRNVAccount: false,
        hasVerifiedBadge: false,
      },
      price: null,
      allowedGearGenres: ["All"],
      allowedGearCategories: [],
      isGenreEnforced: false,
      copyingAllowed: false,
      playing: 4,
      visits: 1538723,
      maxPlayers: 4,
      created: "2024-06-09T15:51:13.02Z",
      updated: "2024-10-12T19:57:00.563Z",
      studioAccessToApisAllowed: false,
      createVipServersAllowed: false,
      universeAvatarType: "MorphToR15",
      genre: "All",
      genre_l1: "Simulation",
      genre_l2: "Tycoon",
      isAllGenre: true,
      isFavoritedByUser: false,
      favoritedCount: 5367,
    },
    {
      id: 6096505120,
      rootPlaceId: 17795196411,
      name: "🎤 Rap and Escape Da Hood Tycoon",
      description:
        "🎤 Rap and Prove Da Hood Wrong Tycoon 🎤\n\nDa hood starts clowning you for not being able to drop hits, so you decide to make albums, blow up, and prove the haters wrong. Start your journey now!!!\n\n🎵 JOIN GROUP FOR 50% CASH BOOST ON MUSIC! 🎵\n🔥 JOIN THE GROUP FOR THE LATEST CODES 🔥\n🎧 Use These Codes after Joining the Group: JOINED 🎧\n💾 Progress is saved automatically 💾\n👍 Leave a like and favorite for more updates, we appreciate it 💯\n\nUpdate 1:\n- Dissed Drake\n\nInspired by sell guns and prove da hood wrong, da hood, baddies, Epic Rap Battles, south bronx",
      sourceName: null,
      sourceDescription: null,
      creator: {
        id: 33447943,
        name: "best tycoons studio",
        type: "Group",
        isRNVAccount: false,
        hasVerifiedBadge: false,
      },
      price: null,
      allowedGearGenres: ["All"],
      allowedGearCategories: [],
      isGenreEnforced: false,
      copyingAllowed: false,
      playing: 0,
      visits: 481973,
      maxPlayers: 4,
      created: "2024-06-09T15:50:00.863Z",
      updated: "2024-10-10T14:01:58.673Z",
      studioAccessToApisAllowed: false,
      createVipServersAllowed: false,
      universeAvatarType: "MorphToR15",
      genre: "All",
      genre_l1: "Simulation",
      genre_l2: "Tycoon",
      isAllGenre: true,
      isFavoritedByUser: false,
      favoritedCount: 4235,
    },
    {
      id: 6096503146,
      rootPlaceId: 17795190380,
      name: "🍡 Mochi Shop Tycoon ",
      description:
        "🍡 Welcome to Mochi Shop Tycoon! 🌸\n\nPrepare mochi in your restaurant then serve it to customers! Build the best mochi store in town!!! 🎀 \n\n-------------\nLead Developer:\nBlestoo: https://www.roblox.com/users/2219075012/profile\n-------------\n\n💃 JOIN GROUP FOR 50% CASH BOOST AND CODES 💃\n💕 USE CODE JOINED AFTER JOINING THE GROUP 💕 \n💾  progress is saved automatically 💾 \n👍 leave a like and favorite if you want more updates, we appreciate it <3 👍 \n\nInspired by badass experiences and joshua \n\n売る もち, 餅\n떡을 팔다\nпродать моти\nขายโมจิ",
      sourceName: null,
      sourceDescription: null,
      creator: {
        id: 33447943,
        name: "best tycoons studio",
        type: "Group",
        isRNVAccount: false,
        hasVerifiedBadge: false,
      },
      price: null,
      allowedGearGenres: ["All"],
      allowedGearCategories: [],
      isGenreEnforced: false,
      copyingAllowed: false,
      playing: 187,
      visits: 12810660,
      maxPlayers: 4,
      created: "2024-06-09T15:49:33.023Z",
      updated: "2025-05-11T01:11:01.84Z",
      studioAccessToApisAllowed: false,
      createVipServersAllowed: false,
      universeAvatarType: "MorphToR15",
      genre: "All",
      genre_l1: "Simulation",
      genre_l2: "Tycoon",
      isAllGenre: true,
      isFavoritedByUser: false,
      favoritedCount: 1346147,
    },
    {
      id: 6043110169,
      rootPlaceId: 17645551479,
      name: "☕ Coffee Cafe Tycoon",
      description:
        "☕ Make and Brew and Sell Coffee to PROVE MOM WRONG! ☕\n\nYour mom doesn't want you to make a coffee factory and he thinks you will FAIL. to prove her wrong, you start building the best cafe ever in this tycoon....\n\n🎮 JOIN GROUP FOR 50% CASH BOOST 🎮\n 🎮 JOIN THE GROUP FOR THE LATEST CODES. 🎮 \n💗 Use These Codes after Joining the Group! JOINED \n💾 progress is saved automatically 💾 \n👍 leave a like and favorite if you want more updates, we appreciate it <3 👍\n\nMAKE SURE TO FOLLOW: https://www.roblox.com/users/628627550 :)\n\nInspired by badass experiences and joshua, and My Coffee Shop ☕,  🍵 Boba Cafe 😋, [UPD] ☕ Cozy Cafe Tycoon and cafe\n\nカフェタイクーンゲームでコーヒー\nกาแฟในเกมผู้ประกอบการร้านกาแฟ\n카페 타이쿤 게임의 커피\ncafé en un juego de magnate del café\nкофе в кафе ролевая игра магнат\ncafé en un café juego de rol magnate\nCoffee, café,  コーヒー, 커피",
      sourceName: null,
      sourceDescription: null,
      creator: {
        id: 33447943,
        name: "best tycoons studio",
        type: "Group",
        isRNVAccount: false,
        hasVerifiedBadge: false,
      },
      price: null,
      allowedGearGenres: ["All"],
      allowedGearCategories: [],
      isGenreEnforced: false,
      copyingAllowed: false,
      playing: 12,
      visits: 3600204,
      maxPlayers: 6,
      created: "2024-05-28T11:38:20.69Z",
      updated: "2025-05-30T10:47:12.987Z",
      studioAccessToApisAllowed: false,
      createVipServersAllowed: false,
      universeAvatarType: "MorphToR15",
      genre: "All",
      genre_l1: "Simulation",
      genre_l2: "Tycoon",
      isAllGenre: true,
      isFavoritedByUser: false,
      favoritedCount: 8042,
    },
    {
      id: 5867733530,
      rootPlaceId: 17126888732,
      name: "🍜 Make Ramen and Prove Dad Wrong",
      description:
        "your dad thinks your ramen is trash... he believes that you will never become successful off of your ramen. to prove him wrong, you must create your own ramen empire tycoon and become the biggest ramen company in the history of robloxia.\n\n🎮 JOIN GROUP FOR 50% CASH BOOST 🎮\n🎮 JOIN THE GROUP FOR THE LATEST CODES. 🎮 \n💗 Use These Codes after Joining the Group! JOINED \n💾 progress is saved automatically 💾 \n👍 leave a like and favorite if you want more updates, we appreciate it <3 👍\n\nLead Creator: TUBSYOLO2 https://www.roblox.com/users/1118823050\n\nUpdate 1:\n- removed kanye\n- added drake\n\nおいしいラーメンを作る\n맛있는 라면을 만들어 보세요\nทำราเมนแสนอร่อย\nприготовить вкусный рамен\n\nInspired by badass experiences and joshua, and sushi tycoon along with boba",
      sourceName: null,
      sourceDescription: null,
      creator: {
        id: 33447943,
        name: "best tycoons studio",
        type: "Group",
        isRNVAccount: false,
        hasVerifiedBadge: false,
      },
      price: null,
      allowedGearGenres: ["All"],
      allowedGearCategories: [],
      isGenreEnforced: false,
      copyingAllowed: false,
      playing: 13,
      visits: 2694341,
      maxPlayers: 4,
      created: "2024-04-13T11:11:05.697Z",
      updated: "2024-10-03T10:57:58.753Z",
      studioAccessToApisAllowed: false,
      createVipServersAllowed: false,
      universeAvatarType: "MorphToR15",
      genre: "All",
      genre_l1: "Simulation",
      genre_l2: "Tycoon",
      isAllGenre: true,
      isFavoritedByUser: false,
      favoritedCount: 22949,
    },
    {
      id: 5867733200,
      rootPlaceId: 17126887209,
      name: "🍣 Sushi Shop Tycoon",
      description:
        "🥢 Welcome To Sell Sushi Tycoon! 🍣\n\n✨ Get Your Own Sushi Conveyor Tycoon And Start Making Sushi ! Sell Them And Upgrade Your Sushi To Be The Best Around The Town!  ✨\n\n-------------\nLead Developer:\nBlestoo: https://www.roblox.com/users/2219075012/profile\n-------------\n\n📜Climb The Leaderboards And Become The Best SUSHI JAPANESE RESTAURANT Owner 🔥\n\n👍 LIKE THE GAME TO BRING BACK CASEOH!\n💵 JOIN THE GROUP FOR 50% CASH BOOST!\n📋 JOIN THE GROUP FOR THE LATEST CODES!\n\nInspired by badass experiences and joshua\n\n맛있는 컨베이어 스시 레스토랑 타이쿤\nおいしい回転寿司店の大物\nผู้ประกอบการร้านอาหารซูชิสายพานลำเลียงแสนอร่อย\ndeclicious conveyor sushi restaurant tycoon\nвкусный конвейер суши ресторан магнат\n\nTags: pizza restaurant real world roleplay pizzeria cafe role play simulation cafe factory pizza worker pizza social hangout sushi game simulator world hotel cafe popular tycoon cafe hotel tycoon tycoon tycoon tycoon tycoon tycoon tycoon tycoon tycoon tycoon tycoon tycoon tycoon tycoon tycoon tycoon tycoon tycoon ",
      sourceName: null,
      sourceDescription: null,
      creator: {
        id: 33447943,
        name: "best tycoons studio",
        type: "Group",
        isRNVAccount: false,
        hasVerifiedBadge: false,
      },
      price: null,
      allowedGearGenres: ["All"],
      allowedGearCategories: [],
      isGenreEnforced: false,
      copyingAllowed: false,
      playing: 46,
      visits: 11365559,
      maxPlayers: 4,
      created: "2024-04-13T11:10:58.73Z",
      updated: "2025-05-11T07:01:45.827Z",
      studioAccessToApisAllowed: false,
      createVipServersAllowed: false,
      universeAvatarType: "MorphToR15",
      genre: "All",
      genre_l1: "Simulation",
      genre_l2: "Tycoon",
      isAllGenre: true,
      isFavoritedByUser: false,
      favoritedCount: 28031,
    },
    {
      id: 5867727690,
      rootPlaceId: 17126870426,
      name: "👸Become a Princess and Prove Mom Wrong",
      description:
        "💃 Dress Up and make your princess\n🏰 Expand your castle\n🌸 Prove mom wrong\n\n🎮 JOIN GROUP FOR 50% CASH BOOST 🎮\n🎮 JOIN THE GROUP FOR THE LATEST CODES. 🎮 \n💗 Use These Codes after Joining the Group! JOINED \n💾 progress is saved automatically 💾 \n👍 leave a like and favorite if you want more updates, we appreciate it <3 👍\n\nお姫様になってかわいい人形を作ろう\n공주가 되어 귀여운 인형을 만들어보세요\nกลายเป็นเจ้าหญิงและทำตุ๊กตาน่ารัก ๆ\n\nInspired by badass experiences and joshua, and mega princess tycoon along with princess tycoon 👸",
      sourceName: null,
      sourceDescription: null,
      creator: {
        id: 33447943,
        name: "best tycoons studio",
        type: "Group",
        isRNVAccount: false,
        hasVerifiedBadge: false,
      },
      price: null,
      allowedGearGenres: ["All"],
      allowedGearCategories: [],
      isGenreEnforced: false,
      copyingAllowed: false,
      playing: 4,
      visits: 6710674,
      maxPlayers: 4,
      created: "2024-04-13T11:09:17.757Z",
      updated: "2024-11-06T15:26:28.53Z",
      studioAccessToApisAllowed: false,
      createVipServersAllowed: false,
      universeAvatarType: "MorphToR15",
      genre: "All",
      genre_l1: "Simulation",
      genre_l2: "Tycoon",
      isAllGenre: true,
      isFavoritedByUser: false,
      favoritedCount: 12635,
    },
    {
      id: 5867727147,
      rootPlaceId: 17126868551,
      name: "🔫 Sell Guns and Prove Da Hood Wrong",
      description:
        "🔫 Sell and Make Guns in the hood tycoon and prove the hood wrong 💣\n\nDa hood starts bullying you for not being tough on the streets, you decide to sell weapons to make it out the hood and prove the haters wrong. Start your journey now!!!\n\n🎮 JOIN GROUP FOR 50% CASH BOOST 🎮\n💯 JOIN THE GROUP FOR THE LATEST CODES. 💯\n💿 Use These Codes after Joining the Group! JOINED \n💾 progress is saved automatically 💾 \n👍 leave a like and favorite if you want more updates, we appreciate it <3 👍\n\nUpdate 1: \n- Removed Drake\n\n銃を作ってギャングになる\n동네 거물에서 총을 만들고 갱스터가 되어보세요\nสร้างปืนในผู้ประกอบการเครื่องดูดควันและเป็นนักเลง\nделать оружие в капюшоне\nconviértete en un gángster y vende armas en el capó\n\nInspired by badass experiences and joshua, and da hood, South Bronx: The Trenches❗,  Hood Modded, SELL POOP TYCOON!",
      sourceName: null,
      sourceDescription: null,
      creator: {
        id: 33447943,
        name: "best tycoons studio",
        type: "Group",
        isRNVAccount: false,
        hasVerifiedBadge: false,
      },
      price: null,
      allowedGearGenres: ["All"],
      allowedGearCategories: [],
      isGenreEnforced: false,
      copyingAllowed: false,
      playing: 33,
      visits: 12613933,
      maxPlayers: 4,
      created: "2024-04-13T11:09:08.62Z",
      updated: "2025-07-03T14:01:15.197Z",
      studioAccessToApisAllowed: false,
      createVipServersAllowed: false,
      universeAvatarType: "MorphToR15",
      genre: "All",
      genre_l1: "Simulation",
      genre_l2: "Tycoon",
      isAllGenre: true,
      isFavoritedByUser: false,
      favoritedCount: 51402,
    },
    {
      id: 5796808845,
      rootPlaceId: 16871857519,
      name: "Sell SHOES Tycoon",
      description:
        "👟 Sell and Make NIKE in the hood tycoon and prove dad wrong 🔥\n\nDad starts shouting at you and wants to kick you out for not being succesfull, you decide to sell some fire NIKE to make it out da hood and prove all those haters wrong. Start your journey now gang!!!\n\n🎮 JOIN GROUP FOR 50% CASH BOOST 🎮\n💯 JOIN THE GROUP FOR THE LATEST CODES. 💯\n💿 Use These Codes after Joining the Group! JOINED SNEAKERS\n💾 progress is saved automatically 💾 \n👍 leave a like and favorite if you want more updates, we appreciate it <3 👍\n\n\nスニーカーの販売と再販のスニーカーシミュレーター、ナイキアディダス\n운동화 판매 및 운동화 시뮬레이터 재판매, 나이키 아디다스\nขายรองเท้าผ้าใบและขายรองเท้าผ้าใบจำลอง\nпродавать кроссовки и перепродавать симулятор кроссовок, Nike Adidas\nvender zapatillas y revender simulador de zapatillas, nike adidas\n\nInspired by badass experiences and joshua, and da hood, South Bronx: The Trenches❗,  Hood Modded, SELL POOP TYCOON!, Sneaker Resell Simulator, sell guns and prove da hood wrong, sneaker, sneakers, shoe, shoes, trading, trade",
      sourceName: null,
      sourceDescription: null,
      creator: {
        id: 33447943,
        name: "best tycoons studio",
        type: "Group",
        isRNVAccount: false,
        hasVerifiedBadge: false,
      },
      price: null,
      allowedGearGenres: ["All"],
      allowedGearCategories: [],
      isGenreEnforced: false,
      copyingAllowed: false,
      playing: 0,
      visits: 185655,
      maxPlayers: 4,
      created: "2024-03-25T20:01:12.177Z",
      updated: "2024-08-22T19:49:45.513Z",
      studioAccessToApisAllowed: false,
      createVipServersAllowed: false,
      universeAvatarType: "MorphToR15",
      genre: "All",
      genre_l1: "",
      genre_l2: "",
      isAllGenre: true,
      isFavoritedByUser: false,
      favoritedCount: 609,
    },
    {
      id: 5796807859,
      rootPlaceId: 16871854967,
      name: " 💄 Sell Makeup and Prove Mom Wrong",
      description:
        "💄 Sell Makeup to PROVE MOM WRONG! 💄 \n\nYour mom doesn't want you to sell makeup and says that ur not pretty... to prove her wrong you build the best makeup store to ever exist! ✨\n\n💅 JOIN GROUP FOR 50% CASH BOOST 💅 \n🎀 JOIN THE GROUP FOR THE LATEST CODES. 🎀 \n💖 USE CODE JOINED AFTER JOINING THE GROUP 💖 \n💾  progress is saved automatically 💾 \n👍 leave a like and favorite if you want more updates, we appreciate it <3 👍 \n\nUpdate: \n- removed drake \n- deleted amber heard \n\n化粧品を販売する\n화장품을 팔다\nсоздавать моду\nขายเครื่องสำอาง\n\nInspired by badass experiences and joshua, and dress to impress",
      sourceName: null,
      sourceDescription: null,
      creator: {
        id: 33447943,
        name: "best tycoons studio",
        type: "Group",
        isRNVAccount: false,
        hasVerifiedBadge: false,
      },
      price: null,
      allowedGearGenres: ["All"],
      allowedGearCategories: [],
      isGenreEnforced: false,
      copyingAllowed: false,
      playing: 14,
      visits: 22935395,
      maxPlayers: 4,
      created: "2024-03-25T20:00:58.797Z",
      updated: "2025-09-22T07:18:49.1071856Z",
      studioAccessToApisAllowed: false,
      createVipServersAllowed: false,
      universeAvatarType: "MorphToR15",
      genre: "All",
      genre_l1: "Simulation",
      genre_l2: "Tycoon",
      isAllGenre: true,
      isFavoritedByUser: false,
      favoritedCount: 62209,
    },
    {
      id: 5757295081,
      rootPlaceId: 16752197913,
      name: "🥤 Make Boba and Prove Mom Wrong ",
      description:
        "🥤Make and Sell Boba to PROVE MOM WRONG! 🥤\n\nYour dad doesn't want you to make a Boba factory and he thinks you will FAIL. to prove him wrong, you start building the best Boba factory ever.... \n\nUPDATE 1\n- Fixed Bugs!\n\n🎮 JOIN GROUP FOR 50% CASH BOOST 🎮\n 🎮 JOIN THE GROUP FOR THE LATEST CODES. 🎮 \n💗 Use These Codes after Joining the Group! JOINED \n💾 progress is saved automatically 💾 \n👍 leave a like and favorite if you want more updates, we appreciate it <3 👍\n\nLead Creator: TUBSYOLO2 https://www.roblox.com/users/1118823050\n\nボバ茶を作る\n보바차를 만들어 보세요\nทำชาไข่มุก\n\nInspired by badass experiences and joshua, and bubble tea tycoon along with boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba boba",
      sourceName: null,
      sourceDescription: null,
      creator: {
        id: 33447943,
        name: "best tycoons studio",
        type: "Group",
        isRNVAccount: false,
        hasVerifiedBadge: false,
      },
      price: null,
      allowedGearGenres: ["All"],
      allowedGearCategories: [],
      isGenreEnforced: false,
      copyingAllowed: false,
      playing: 50,
      visits: 27761740,
      maxPlayers: 4,
      created: "2024-03-15T15:58:30.33Z",
      updated: "2025-08-27T07:02:21.78Z",
      studioAccessToApisAllowed: false,
      createVipServersAllowed: false,
      universeAvatarType: "MorphToR15",
      genre: "All",
      genre_l1: "Simulation",
      genre_l2: "Tycoon",
      isAllGenre: true,
      isFavoritedByUser: false,
      favoritedCount: 80133,
    },
    {
      id: 5703097486,
      rootPlaceId: 16568963921,
      name: "⛩️ Make Katanas and Prove Sensei Wrong",
      description:
        "⛩️ Make and Sell Anime Swords and Katanas to PROVE SENSEI WRONG! ⛩️\n\nYour sensei from anime doesn't want you to become a samurai ninja and make a Katana factory and he thinks you will FAIL. to prove him wrong, you start building the best Katana blacksmith forge ever.... \n\n🎮 JOIN GROUP FOR 50% CASH BOOST 🎮\n🎮 JOIN THE GROUP FOR THE LATEST CODES. 🎮 \n💗 Use These Codes after Joining the Group! JOINED \n💾 progress is saved automatically 💾 \n👍 leave a like and favorite if you want more updates, we appreciate it <3 👍\n\n忍者になる, 先生になる, 刀を作る\n사무라이가 되다, 닌자가 되다, 카타나를 만들어라\nกลายเป็นซามูไร, กลายเป็นนินจา, ทำคาทาน่า\nстать самураем, стать ниндзя, сделать катану\n\nInspired by badass experiences and joshua, and ZO SAMURAI SWORD FIGHTING along with Ninja Legends Tycoon\n\nBuilt by https://www.roblox.com/users/35529078/profile : )",
      sourceName: null,
      sourceDescription: null,
      creator: {
        id: 33447943,
        name: "best tycoons studio",
        type: "Group",
        isRNVAccount: false,
        hasVerifiedBadge: false,
      },
      price: null,
      allowedGearGenres: ["All"],
      allowedGearCategories: [],
      isGenreEnforced: false,
      copyingAllowed: false,
      playing: 4,
      visits: 4872946,
      maxPlayers: 4,
      created: "2024-02-29T17:36:07.99Z",
      updated: "2025-01-20T15:15:08.957Z",
      studioAccessToApisAllowed: false,
      createVipServersAllowed: false,
      universeAvatarType: "MorphToR15",
      genre: "All",
      genre_l1: "Simulation",
      genre_l2: "Tycoon",
      isAllGenre: true,
      isFavoritedByUser: false,
      favoritedCount: 29887,
    },
    {
      id: 5703096635,
      rootPlaceId: 16568959366,
      name: "🍕Pizza Place Tycoon",
      description:
        "Welcome to 🍕 Pizza Place Tycoon!\n\n🍕 Become a cook and make pizzas!\n👨‍🍳 Hire chefs and cashiers!\n💵 Earn money and upgrade your restaurant!\n🧹 Make sure to keep your pizza place clean!\n\nCodes: JOINED, RELEASE\nMake sure to LIKE and FAVORITE for more updates!\n\nRemember to always say I Cook'a the Pizza!\n\nInspired by badass experiences and joshua\nAlso inspired by 🍕Work at a Pizza Place and Escape Papa Pizza's Pizzeria! (SCARY OBBY) and 🍕 Pizzeria Tycoon 2 and the famous Pizza Factory Tycoon\n\nTags: sandwich burger restaurant real world roleplay subway mcdonalds, food, restaurant, burgers sandwich restaurant cafe role play simulation cafe factory sandwich worker pizza social hangout sushi game simulator world hotel cafe popular tycoon cafe hotel tycoon tycoon tycoon tycoon tycoon tycoon tycoon tycoon tycoon tycoon tycoon tycoon tycoon tycoon tycoon tycoon tycoon tycoon ",
      sourceName: null,
      sourceDescription: null,
      creator: {
        id: 33447943,
        name: "best tycoons studio",
        type: "Group",
        isRNVAccount: false,
        hasVerifiedBadge: false,
      },
      price: null,
      allowedGearGenres: ["All"],
      allowedGearCategories: [],
      isGenreEnforced: false,
      copyingAllowed: false,
      playing: 2,
      visits: 3677862,
      maxPlayers: 4,
      created: "2024-02-29T17:35:46.81Z",
      updated: "2025-01-13T13:11:42.187Z",
      studioAccessToApisAllowed: false,
      createVipServersAllowed: false,
      universeAvatarType: "MorphToR15",
      genre: "All",
      genre_l1: "Simulation",
      genre_l2: "Tycoon",
      isAllGenre: true,
      isFavoritedByUser: false,
      favoritedCount: 289318,
    },
    {
      id: 5703095385,
      rootPlaceId: 16568954289,
      name: "build area 51 and and prove aliens wrong",
      description:
        "🧪 You know that aliens are real, you build a bunker and prove the world that aliens indeed exist... 👽\n\nSell your research for money!\nGet rid of FBIs for extra money!\n\nLike the game to support us!\n\n⚠️ HOW TO SELL: There are 2 researchers on the both sides of the map, where you can sell research at from your tycoon! Use your vehicle to drive to that location.\n\nLead Developer\nBlestoo: https://www.roblox.com/users/2219075012/profile\n\nTags: zombie, tycoon, survive, bunker, build to survive, zombies, tycoons, fun, undead, defense, survival, invasion, apocalypse, alien, area 51, fun!\n\n외계인 벙커 거물\nエイリアンバンカーの大物\nบังเกอร์กุนคนต่างด้าว\nинопланетный бункерный магнат",
      sourceName: null,
      sourceDescription: null,
      creator: {
        id: 33447943,
        name: "best tycoons studio",
        type: "Group",
        isRNVAccount: false,
        hasVerifiedBadge: false,
      },
      price: null,
      allowedGearGenres: ["All"],
      allowedGearCategories: [],
      isGenreEnforced: false,
      copyingAllowed: false,
      playing: 3,
      visits: 1795543,
      maxPlayers: 6,
      created: "2024-02-29T17:35:15.863Z",
      updated: "2025-04-11T06:16:35.353Z",
      studioAccessToApisAllowed: false,
      createVipServersAllowed: false,
      universeAvatarType: "MorphToR6",
      genre: "All",
      genre_l1: "Simulation",
      genre_l2: "Tycoon",
      isAllGenre: true,
      isFavoritedByUser: false,
      favoritedCount: 3011,
    },
    {
      id: 5703094458,
      rootPlaceId: 16568950656,
      name: "Pet Shop Tycoon (CAPYBARA)",
      description:
        "🧽 Take care of Animals and sell them to your friends for Cash!\nCollect more animals, clean them up, feed them, and grow your tycoon!\n💸 Unlock more animals and earn bigger rewards.\n\n🔄 Rebirth for higher cash multipliers once your tycoon is complete!\n\n💬 Suggestions or Bugs?\nPost them on our group wall!\n\n💰 Group Members: Earn 20% more cash.\n\n👍 Like and favorite if you’re enjoying the game!\n🌐 A strong internet connection is recommended for the best experience.\n\ncửa hàng thú cưng của tôi\n私のペットショップ\nмой зоомагазин\n내 애완동물 가게\nร้านขายสัตว์เลี้ยงของฉัน\nMultimilyonaryan tindahan ng alaga",
      sourceName: null,
      sourceDescription: null,
      creator: {
        id: 33447943,
        name: "best tycoons studio",
        type: "Group",
        isRNVAccount: false,
        hasVerifiedBadge: false,
      },
      price: null,
      allowedGearGenres: ["All"],
      allowedGearCategories: [],
      isGenreEnforced: false,
      copyingAllowed: false,
      playing: 8,
      visits: 5060479,
      maxPlayers: 4,
      created: "2024-02-29T17:34:54.247Z",
      updated: "2024-11-17T23:28:18.8Z",
      studioAccessToApisAllowed: false,
      createVipServersAllowed: false,
      universeAvatarType: "PlayerChoice",
      genre: "All",
      genre_l1: "Simulation",
      genre_l2: "Tycoon",
      isAllGenre: true,
      isFavoritedByUser: false,
      favoritedCount: 15165,
    },
    {
      id: 5671290754,
      rootPlaceId: 16462511715,
      name: "🏠 BUILD HOUSES TO PROVE DAD WRONG",
      description:
        "🏠 you've had enough of living at The Lagoons for the past 30 years. they believe their houses are the best, but its really bad, ITS TRASH. to prove them wrong, you decide to make your own building company to out-build The Lagoons.\n\n👍 LIKE THE GAME TO BRING BACK KANYE\n💵 JOIN THE GROUP FOR 50% CASH BOOST\n📋 JOIN THE GROUP FOR THE LATEST CODES\n\nCodes: JOINED, RELEASE\nInspired by badass experiences and joshua\n\n良い建物を作ってください\n좋은 건물을 만들어라\nสร้างอาคารที่ดี",
      sourceName: null,
      sourceDescription: null,
      creator: {
        id: 33447943,
        name: "best tycoons studio",
        type: "Group",
        isRNVAccount: false,
        hasVerifiedBadge: false,
      },
      price: null,
      allowedGearGenres: ["All"],
      allowedGearCategories: [],
      isGenreEnforced: false,
      copyingAllowed: false,
      playing: 0,
      visits: 2667284,
      maxPlayers: 4,
      created: "2024-02-21T14:21:47.437Z",
      updated: "2025-07-07T11:15:23.643Z",
      studioAccessToApisAllowed: false,
      createVipServersAllowed: false,
      universeAvatarType: "MorphToR15",
      genre: "All",
      genre_l1: "Simulation",
      genre_l2: "Tycoon",
      isAllGenre: true,
      isFavoritedByUser: false,
      favoritedCount: 9328,
    },
    {
      id: 5560901908,
      rootPlaceId: 16089922208,
      name: "💅Be A Baddie To Prove Mom Wrong",
      description:
        '💅One day while trying to be a Baddie, you decide to leave forever because you\'re a failure. You must climb the ranks and become the best Baddie to prove your family wrong and win them back. Become a Baddie and Prove Mom Wrong and Prove Dad Wrong by being a real Baddie to your friends. 💅\n\n👍LEAVE A LIKE AND FAVORITE TO BE A BADDIE AND FOR MORE UPDATES!! 👍 \n\n🎮 JOIN GROUP AND LIKE THE GAME FOR 50% CASH BOOST 🎮\n💕 JOIN THE GROUP FOR THE LATEST CODES 💕\n💾 Progress is saved automatically 💾 \nCodes: "Release", "Joined" \nJOIN THE GROUP FOR THE LATEST CODES. THIRD FLOOR AND BASEMENT COMING SOON!!!\n\nInspired by badass experiences and joshua, and BADDIES, Baddies, Florida, Bad Girls, South, hood, west, battlegrounds, Roleplay, Hosted, Freeplay.\nhood, South Bronx: The Trenches❗,  Hood Modded',
      sourceName: null,
      sourceDescription: null,
      creator: {
        id: 33447943,
        name: "best tycoons studio",
        type: "Group",
        isRNVAccount: false,
        hasVerifiedBadge: false,
      },
      price: null,
      allowedGearGenres: ["All"],
      allowedGearCategories: [],
      isGenreEnforced: false,
      copyingAllowed: false,
      playing: 68,
      visits: 23494009,
      maxPlayers: 4,
      created: "2024-01-23T19:51:46.117Z",
      updated: "2025-04-16T20:54:48.62Z",
      studioAccessToApisAllowed: false,
      createVipServersAllowed: false,
      universeAvatarType: "MorphToR15",
      genre: "All",
      genre_l1: "Simulation",
      genre_l2: "Tycoon",
      isAllGenre: true,
      isFavoritedByUser: false,
      favoritedCount: 66885,
    },
    {
      id: 5560899121,
      rootPlaceId: 16089912078,
      name: "🍰 PROVE GRANDMA WRONG BY BAKING CAKES!",
      description:
        "⭐Make and sell cakes to prove mom wrong! ⭐\n\nYour mom doesn't want you to make or sell cakes and she thinks you WILL FAIL. To prove her wrong, you start building the best cake factory ever created....\n\n🎮 JOIN THE GROUP FOR A 50% CASH INCREASE 🎮\n🎮 JOIN THE GROUP TO GET THE LATEST CODES. 🎮\n⭐ Use these codes after joining the group! UNITED, OPTIMIZATION\n💾 progress is automatically saved 💾\n👍 leave a like and favorite if you want more updates, we appreciate it <3 👍",
      sourceName: null,
      sourceDescription: null,
      creator: {
        id: 33447943,
        name: "best tycoons studio",
        type: "Group",
        isRNVAccount: false,
        hasVerifiedBadge: false,
      },
      price: null,
      allowedGearGenres: ["All"],
      allowedGearCategories: [],
      isGenreEnforced: false,
      copyingAllowed: false,
      playing: 0,
      visits: 666291,
      maxPlayers: 4,
      created: "2024-01-23T19:50:41.917Z",
      updated: "2024-02-13T20:55:13.517Z",
      studioAccessToApisAllowed: false,
      createVipServersAllowed: false,
      universeAvatarType: "MorphToR15",
      genre: "All",
      genre_l1: "Simulation",
      genre_l2: "Tycoon",
      isAllGenre: true,
      isFavoritedByUser: false,
      favoritedCount: 3477,
    },
    {
      id: 5476746717,
      rootPlaceId: 15838031708,
      name: "[⚠️CHAPTER 2] weird strict teacher",
      description:
        "🔥 CHAPTER 2 IS OUT!! PLAY NOW!!! 🔥\n\nwelcome to WEIRD STRICT TEACHER!\n\nAfter a long day at school, you're ready to go home. Except you can't, because the teacher said you didn't work hard enough. Now you must stay overnight, do as he says, study, and survive until daybreak!\n\n🔥[UPDATE 14]🔥\n-🏛️ added CHAPTER 2  🏛️\n- explore the second chapter of weird strict teacher, THE MUSEUM, OUT NOW!!!\n- compete with your friends to get the BEST TIME\n\n(Can be played on all platforms! Controls are shown in-game!)\n\nLeave a LIKE 👍 + FAVORITE ⭐ for updates!\nJoin the group! 🧊\n\nLead Dev: Kthulu\n\nInspired by weird strict dad & weird strict boss\n\nSimilar To: \nweird strict grandma, weird strict, strict, weird, dad, grandma, grandpa, horror, crazy, crazy grandma, weird strict dad, study, studying, mom, sus, weird sus grandma, weird strange librarian, evil, weird evil boss, weird strict, weird\n\n엄격한 선생님을 찾아라\n厳しい先生に気をつけてください\ncuidado con el maestro estricto\nมองหาครูที่เข้มงวด",
      sourceName: null,
      sourceDescription: null,
      creator: {
        id: 33447943,
        name: "best tycoons studio",
        type: "Group",
        isRNVAccount: false,
        hasVerifiedBadge: false,
      },
      price: null,
      allowedGearGenres: ["All"],
      allowedGearCategories: [],
      isGenreEnforced: false,
      copyingAllowed: false,
      playing: 44,
      visits: 36206168,
      maxPlayers: 20,
      created: "2024-01-01T21:44:28.39Z",
      updated: "2025-08-12T10:54:53.377Z",
      studioAccessToApisAllowed: false,
      createVipServersAllowed: false,
      universeAvatarType: "MorphToR6",
      genre: "All",
      genre_l1: "Adventure",
      genre_l2: "Story",
      isAllGenre: true,
      isFavoritedByUser: false,
      favoritedCount: 66282,
    },
    {
      id: 5476740185,
      rootPlaceId: 15838011628,
      name: "📱PROVE DAD WRONG BY MAKING PHONES",
      description:
        "your dad thinks your phones are trash... he believes that you will never become successful off of your phones. to prove him wrong, you must create your own phone empire tycoon and become the biggest phone company in the history of robloxia.\n\n💵 JOIN GROUP FOR 50% CASH BOOST\n⚙ JOIN THE GROUP FOR THE LATEST CODES.\n\nLead Creator: TUBSYOLO2 https://www.roblox.com/users/1118823050\n\nUpdate 1:\n\n- removed kanye\n\nInspired by badass experiences and joshua\n\n未来的な携帯電話を販売しましょう！\n미래형 휴대폰을 판매하세요!\nVende teléfonos futuristas!\nПродавайте лучшие телефоны!",
      sourceName: null,
      sourceDescription: null,
      creator: {
        id: 33447943,
        name: "best tycoons studio",
        type: "Group",
        isRNVAccount: false,
        hasVerifiedBadge: false,
      },
      price: null,
      allowedGearGenres: ["All"],
      allowedGearCategories: [],
      isGenreEnforced: false,
      copyingAllowed: false,
      playing: 178,
      visits: 39478596,
      maxPlayers: 4,
      created: "2024-01-01T21:42:16.613Z",
      updated: "2025-08-14T00:17:26.747Z",
      studioAccessToApisAllowed: false,
      createVipServersAllowed: false,
      universeAvatarType: "MorphToR15",
      genre: "All",
      genre_l1: "Simulation",
      genre_l2: "Tycoon",
      isAllGenre: true,
      isFavoritedByUser: false,
      favoritedCount: 83871,
    },
    {
      id: 5476738268,
      rootPlaceId: 15838005248,
      name: "👮 weird strict police [NEW]",
      description:
        "The execution date is tomorrow, and you are trapped in a jail cell. The evil officer wont let you out no matter what. Can you survive the night to escape? 🚔🚨\n\nCan be played on all platforms\nControls are shown in-game\n\nLeave a LIKE 👍 + FAVORITE ⭐ for updates!\nJoin the group! 🎁\nAvailable on PC/Laptop/Tablet/Phone/Xbox/PlayStation. 📱💻\n\nInspired by weird strict dad\n\nSimilar To: \nweird strict grandma, weird strict, strict, weird, dad, grandma, teacher, horror, crazy, crazy police, weird strict dad, cop, caught, jailed, prisoner, sus, weird sus grandma, weird strange librarian, evil, weird evil boss, weird strict, police, police station, criminals, jail\n\n警察から逃げる\nหลบหนีตำรวจ\n경찰을 피해\nescapar de la policía\nсбежать от полиции",
      sourceName: null,
      sourceDescription: null,
      creator: {
        id: 33447943,
        name: "best tycoons studio",
        type: "Group",
        isRNVAccount: false,
        hasVerifiedBadge: false,
      },
      price: null,
      allowedGearGenres: ["Scary"],
      allowedGearCategories: [],
      isGenreEnforced: false,
      copyingAllowed: false,
      playing: 1,
      visits: 3800353,
      maxPlayers: 20,
      created: "2024-01-01T21:41:38.363Z",
      updated: "2024-05-29T19:14:09.257Z",
      studioAccessToApisAllowed: false,
      createVipServersAllowed: false,
      universeAvatarType: "MorphToR6",
      genre: "Horror",
      genre_l1: "Adventure",
      genre_l2: "Story",
      isAllGenre: false,
      isFavoritedByUser: false,
      favoritedCount: 9040,
    },
    {
      id: 5465729702,
      rootPlaceId: 15809452257,
      name: "🍰 Sell Cakes and PROVE MOM WRONG!",
      description:
        "⭐Make and Sell Cakes to PROVE MOM WRONG! ⭐\n\nYour mom doesn't want you to make and sell cakes and she thinks you will FAIL. to prove her wrong, you start building the best cake factory ever.... \n\n🎮 JOIN GROUP FOR 50% CASH BOOST 🎮\n🎮 JOIN THE GROUP FOR THE LATEST CODES. 🎮 \n⭐ Use These Codes after Joining the Group! JOINED, OPTIMIZATION \n💾 progress is saved automatically 💾 \n👍 leave a like and favorite if you want more updates, we appreciate it <3 👍",
      sourceName: null,
      sourceDescription: null,
      creator: {
        id: 33447943,
        name: "best tycoons studio",
        type: "Group",
        isRNVAccount: false,
        hasVerifiedBadge: false,
      },
      price: null,
      allowedGearGenres: ["Funny"],
      allowedGearCategories: [],
      isGenreEnforced: false,
      copyingAllowed: false,
      playing: 0,
      visits: 748567,
      maxPlayers: 4,
      created: "2023-12-30T15:56:15.527Z",
      updated: "2025-04-21T05:39:05.04Z",
      studioAccessToApisAllowed: false,
      createVipServersAllowed: false,
      universeAvatarType: "MorphToR15",
      genre: "Comedy",
      genre_l1: "Simulation",
      genre_l2: "Tycoon",
      isAllGenre: false,
      isFavoritedByUser: false,
      favoritedCount: 4865,
    },
    {
      id: 5465727031,
      rootPlaceId: 15809444602,
      name: "[🌭] SELL HOTDOGS AND PROVE DAD WRONG",
      description:
        "🌭 Make and Sell Hotdogs to PROVE YOUR DAD WRONG 🌭\n \nYour dad doesn't want you to become a Hotdog Vendor and he thinks you will FAIL. You decide to prove him wrong by becoming a successful Hotdog Vendor and winning him back\n\n 🎮 JOIN GROUP FOR 50% CASH BOOST 🎮 \n\n🎮 JOIN THE GROUP FOR THE LATEST CODES. 🎮 \n\n⭐ Use These Codes after Joining the Group! JOINED \n\n💾 progress is saved automatically 💾 \n\n👍 leave a like and favorite if you want more updates, we appreciate it <3 👍 \n\n\nおいしいホットドッグを作ってください\n 맛있는 핫도그를 만들어보세요\nทำฮอทด็อกแสนอร่อย\ncachorros-quentes saborosos\nприготовить вкусные хот-доги\nhacer deliciosos perritos calientes",
      sourceName: null,
      sourceDescription: null,
      creator: {
        id: 33447943,
        name: "best tycoons studio",
        type: "Group",
        isRNVAccount: false,
        hasVerifiedBadge: false,
      },
      price: null,
      allowedGearGenres: ["All"],
      allowedGearCategories: [],
      isGenreEnforced: false,
      copyingAllowed: false,
      playing: 7,
      visits: 3139259,
      maxPlayers: 4,
      created: "2023-12-30T15:55:32.657Z",
      updated: "2025-04-23T19:31:35Z",
      studioAccessToApisAllowed: false,
      createVipServersAllowed: false,
      universeAvatarType: "MorphToR15",
      genre: "All",
      genre_l1: "Simulation",
      genre_l2: "Tycoon",
      isAllGenre: true,
      isFavoritedByUser: false,
      favoritedCount: 7163,
    },
    {
      id: 5465725011,
      rootPlaceId: 15809438989,
      name: "🍣 MAKE SUSHI AND PROVE DAD WRONG",
      description:
        "🍣 you've had enough of eating at The Sushi for the past 30 years. they believe their sushi is the best, but it really tastes like trash. to prove them wrong, you decide to make your own sushi restaurant to out-sushi The Sushi.\n\n👍 LIKE THE GAME TO BRING BACK KANYE\n💵 JOIN THE GROUP FOR 50% CASH BOOST\n📋 JOIN THE GROUP FOR THE LATEST CODES\n\nCodes: JOINED, RELEASE\nInspired by badass experiences and joshua\n\nおいしいお寿司を作ってください\n맛있는 초밥을 만들어 보세요\nทำซูชิแสนอร่อย",
      sourceName: null,
      sourceDescription: null,
      creator: {
        id: 33447943,
        name: "best tycoons studio",
        type: "Group",
        isRNVAccount: false,
        hasVerifiedBadge: false,
      },
      price: null,
      allowedGearGenres: ["Funny"],
      allowedGearCategories: [],
      isGenreEnforced: false,
      copyingAllowed: false,
      playing: 94,
      visits: 24893113,
      maxPlayers: 4,
      created: "2023-12-30T15:55:00.087Z",
      updated: "2025-08-08T08:19:28.637Z",
      studioAccessToApisAllowed: false,
      createVipServersAllowed: false,
      universeAvatarType: "MorphToR15",
      genre: "Comedy",
      genre_l1: "Simulation",
      genre_l2: "Tycoon",
      isAllGenre: false,
      isFavoritedByUser: false,
      favoritedCount: 90576,
    },
    {
      id: 5465723073,
      rootPlaceId: 15809433722,
      name: "🍫 PROVE DAD WRONG BY MAKING CHOCOLATES",
      description:
        "🍫 Make and Sell CHOCOLATES to PROVE DAD WRONG! 🍫\n\nYou've had about ENOUGH of all those cheap chocolate brands. For years they've been the most popular around the world, while in reality THEY TASTE HORRIBLE! To prove both them and dad wrong, you start off your own chocolate brand within Wonka's chocolate factory tycoon!\n\n👍 LIKE THE GAME TO BRING BACK KANYE\n💵 JOIN THE GROUP FOR 50% CASH BOOST\n📋 JOIN THE GROUP FOR THE LATEST CODES\n\nCodes: JOINED, RELEASE\nInspired by badass experiences and joshua\n\nおいしいチョコレートを作りましょう\n맛있는 초콜릿을 만들어보세요\nทำช็อคโกแลตแสนอร่อย",
      sourceName: null,
      sourceDescription: null,
      creator: {
        id: 33447943,
        name: "best tycoons studio",
        type: "Group",
        isRNVAccount: false,
        hasVerifiedBadge: false,
      },
      price: null,
      allowedGearGenres: ["All"],
      allowedGearCategories: [],
      isGenreEnforced: false,
      copyingAllowed: false,
      playing: 7,
      visits: 8321369,
      maxPlayers: 4,
      created: "2023-12-30T15:54:29.897Z",
      updated: "2025-06-04T00:12:35.137Z",
      studioAccessToApisAllowed: false,
      createVipServersAllowed: false,
      universeAvatarType: "MorphToR15",
      genre: "All",
      genre_l1: "Simulation",
      genre_l2: "Tycoon",
      isAllGenre: true,
      isFavoritedByUser: false,
      favoritedCount: 22693,
    },
    {
      id: 5465268444,
      rootPlaceId: 15808174508,
      name: "🍦 SELL ICECREAM TO PROVE MOM WRONG",
      description:
        "your mom tried your latest ice cream and thinks its trash, and tells you that u will never be good at making ice cream, prove her wrong by making a ice cream empire in your town\n\n💵 JOIN GROUP FOR 50% CASH BOOST\n⚙ JOIN THE GROUP FOR THE LATEST CODES.\n\nInspired by badass experiences and joshua",
      sourceName: null,
      sourceDescription: null,
      creator: {
        id: 33447943,
        name: "best tycoons studio",
        type: "Group",
        isRNVAccount: false,
        hasVerifiedBadge: false,
      },
      price: null,
      allowedGearGenres: ["Funny"],
      allowedGearCategories: [],
      isGenreEnforced: false,
      copyingAllowed: false,
      playing: 0,
      visits: 2334358,
      maxPlayers: 4,
      created: "2023-12-30T13:53:00.697Z",
      updated: "2024-04-27T20:35:45.133Z",
      studioAccessToApisAllowed: false,
      createVipServersAllowed: false,
      universeAvatarType: "MorphToR15",
      genre: "Comedy",
      genre_l1: "Simulation",
      genre_l2: "Tycoon",
      isAllGenre: false,
      isFavoritedByUser: false,
      favoritedCount: 9000,
    },
    {
      id: 5422556080,
      rootPlaceId: 15696873317,
      name: "🍔MAKE BURGERS AND PROVE DAD WRONG",
      description:
        "Your dad doesn't want you to cook burgers and he thinks you will FAIL.\nYou decide to prove him wrong by becoming a famous chef whose burgers are on top of the world and win him back!\n\n🎮 JOIN GROUP FOR 50% CASH BOOST 🎮\n🎮 JOIN THE GROUP FOR THE LATEST CODES. 🎮 \n\n⭐ Use These Codes after Joining the Group! JOINED\n💾 progress is saved automatically 💾 \n👍 leave a like and favorite if you want more updates, we appreciate it <3 👍\n\nhacer unas buenas hamburguesas\nおいしいハンバーガーを作ってください\n맛있는 버거 좀 만들어\nприготовь хорошие гамбургеры",
      sourceName: null,
      sourceDescription: null,
      creator: {
        id: 33447943,
        name: "best tycoons studio",
        type: "Group",
        isRNVAccount: false,
        hasVerifiedBadge: false,
      },
      price: null,
      allowedGearGenres: ["Funny"],
      allowedGearCategories: [],
      isGenreEnforced: false,
      copyingAllowed: false,
      playing: 7,
      visits: 4764257,
      maxPlayers: 4,
      created: "2023-12-21T01:05:22.7Z",
      updated: "2025-03-25T02:27:36.85Z",
      studioAccessToApisAllowed: false,
      createVipServersAllowed: false,
      universeAvatarType: "MorphToR15",
      genre: "Comedy",
      genre_l1: "Simulation",
      genre_l2: "Tycoon",
      isAllGenre: false,
      isFavoritedByUser: false,
      favoritedCount: 11401,
    },
    {
      id: 5393919660,
      rootPlaceId: 15620723583,
      name: "Make Donuts and Prove Mom Wrong",
      description:
        "Become the biggest donut factory ever\n\n💵 JOIN GROUP FOR 50% CASH BOOST\n⚙ JOIN THE GROUP FOR THE LATEST CODES.\n\nInspired by badass experiences and joshua\n\nおいしいドーナツを作りましょう\nДелайте вкусные пончики\n맛있는 도넛을 만들어보세요\nhacer deliciosas donas",
      sourceName: null,
      sourceDescription: null,
      creator: {
        id: 33447943,
        name: "best tycoons studio",
        type: "Group",
        isRNVAccount: false,
        hasVerifiedBadge: false,
      },
      price: null,
      allowedGearGenres: ["Funny"],
      allowedGearCategories: [],
      isGenreEnforced: false,
      copyingAllowed: false,
      playing: 15,
      visits: 9511366,
      maxPlayers: 4,
      created: "2023-12-13T02:57:05.187Z",
      updated: "2025-04-01T08:37:25.49Z",
      studioAccessToApisAllowed: false,
      createVipServersAllowed: false,
      universeAvatarType: "MorphToR15",
      genre: "Comedy",
      genre_l1: "Simulation",
      genre_l2: "Tycoon",
      isAllGenre: false,
      isFavoritedByUser: false,
      favoritedCount: 30901,
    },
    {
      id: 5348751137,
      rootPlaceId: 15500517226,
      name: "🍕 PROVE DAD WRONG BY COOKING PIZZA",
      description:
        "you've had enough of eating at The Hut for the past 30 years. they believe their pizza is the best, but it really tastes like trash. to prove them wrong, you decide to make your own pizza restaurant to out-pizza The Hut.\n\n👍 LIKE THE GAME TO BRING BACK KANYE\n💵 JOIN THE GROUP FOR 50% CASH BOOST\n📋 JOIN THE GROUP FOR THE LATEST CODES\n\nCodes: JOINED, RELEASE\nInspired by badass experiences and joshua\n\nприготовить вкусную пиццу\n맛있는 피자 만들기\nおいしいピザを作る\nhacer una pizza sabrosa",
      sourceName: null,
      sourceDescription: null,
      creator: {
        id: 33447943,
        name: "best tycoons studio",
        type: "Group",
        isRNVAccount: false,
        hasVerifiedBadge: false,
      },
      price: null,
      allowedGearGenres: ["Funny"],
      allowedGearCategories: [],
      isGenreEnforced: false,
      copyingAllowed: false,
      playing: 12,
      visits: 10738855,
      maxPlayers: 4,
      created: "2023-11-29T23:11:55.857Z",
      updated: "2025-03-25T02:29:24.013Z",
      studioAccessToApisAllowed: false,
      createVipServersAllowed: false,
      universeAvatarType: "MorphToR15",
      genre: "Comedy",
      genre_l1: "Simulation",
      genre_l2: "Tycoon",
      isAllGenre: false,
      isFavoritedByUser: false,
      favoritedCount: 40060,
    },
  ];

  res.status(200).json(games);
}
